name: CI

on: [push]

jobs:
  job1:
    runs-on: macOS-latest
    steps:
    - uses: ozonelmy/Hippy@master
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
